### ISSUE TITLE
Does not compile with Agda 2.5.2

### ISSUE THREAD

**Issue by JoeyEremondi** [effectfully/Generic#1]
SSCCE:

```agda
import Generic.Lib.Prelude as Generic
open import Generic.Main using (deriveEqTo)

open import Data.List

instance
    ListEq : {A : Set} {{eqA : Generic.Eq A}} -> Generic.Eq (List A)
    unquoteDef ListEq = deriveEqTo ListEq (quote List)

```

Gives the error:

> the return type must be μ
> when checking that the expression
> unquote
> (Generic.Main.gcoerce (quote .EqTest.foldAgda.Builtin.List.List))
> has type List A → .EqTest.Agda.Builtin.List.List′ A

I know nothing about Agda reflection/deriving, but I'll try to do some reading to see if I can figure out what's changed with this version.

**Comment by effectfully** [comment]
The library was type checked with the development version of Agda (2.6.0), so it can well be due to distinctions between development and released version of Agda. I checked whether all the bugs I reported are fixed in 2.5.2 and it seems so. I *almost* installed Agda 2.5.2, so I'll maybe have some luck to dive into the bug on the weekend.

Meanwhile, the function to blame is

```
onFinalMu : ∀ {α} {A : Set α} -> (∀ {ι β} {I : Set ι} -> Data (Desc I β) -> TC A) -> Type -> TC A
onFinalMu k = monoLastType >>> λ
  { appDef (quote μ) (...) -> ...
  ;  _ -> throw "the return type must be μ"
  }
```

which calls

```
monoLastType : Type -> Type
monoLastType = go 0 where
  go : ℕ -> Type -> Type
  go n (pi s a b) = go (suc n) b
  go n  b         = unshiftBy n b
```

i.e. the last type (the second argument of the last pi in a type) is not `μ` applied to something, which is weird. This can be due to the fact that in `gcoerce`

```
  gcoerce : Name -> Term -> TC _
  gcoerce fd ?r = inferType ?r >>= onFinalMu λ{ D@(packData _ _ b _ _) ->
      quoteTC (μ D) >>= λ μD ->
      traverseAll quoteTC (allCons D) >>= λ cs′ ->
      unify ?r $ vis appDef fd (curryBy b μD ∷ allToList cs′)
    }
```

`inferType ?r` doesn't actually infer the type of `?r`, but this seems unlikely. Anyway, I'll start from printing what `inferType ?r` returns (via `typeError` and `termErr`).

Thank you for the report.

**Comment by effectfully** [comment]
OK, I've installed Agda-2.5.2, so don't bother debugging this.

**Comment by effectfully** [comment]
It's indeed the case that `inferType` doesn't infer the type of `?r` properly, because `inferType` doesn't now normalize the inferred type. [From the changelog](https://github.com/agda/agda/blob/master/CHANGELOG.md):

> The TC primitives `inferType`, `checkType` and `quoteTC` no longer normalise their arguments.

I've fixed the bug and now all tests pass except for this one:

```
test₂ : xs ≟ (2 ∷ᵥ 4 ∷ᵥ 2 ∷ᵥ []ᵥ) ≡ no _
test₂ = refl
```

which seems to make Agda loop. I think it's an Agda bug, because this test passes:

```
test₂ : xs == (2 ∷ᵥ 4 ∷ᵥ 2 ∷ᵥ []ᵥ) ≡ false
test₂ = refl
```

I'll report this later, so not closing the issue right now.

**Comment by JoeyEremondi** [comment]
Thanks, that works for me! And thanks for your great work on this library, it's really a lifesaver for me.

**Comment by effectfully** [comment]
I'm glad you liked the library. Could you please report later whether it suits your needs properly? Any kind of feedback is highly appreciated: feature requests, reports about problems with deriving or performance (the library is slow and I don't know what to do with that) or whatsoever. And feel free to ask questions if you have any.

**Comment by effectfully** [comment]
With Agda 2.5.3 the

```agda
test₂ : xs ≟ (2 ∷ᵥ 4 ∷ᵥ 2 ∷ᵥ []ᵥ) ≡ no _
test₂ = refl
```

takes a bit long to type check, but type checks successfully, so I'm closing this.
