### ISSUE TITLE
Various issues in `Generic.Function.Lookup`

### ISSUE THREAD

**Issue by alexarice** [effectfully/Generic#4]
Trying to build v0.1 for https://github.com/NixOS/nixpkgs/pull/95059 but hitting some issues in `Generic.Function.Lookup`
It seems \oplus is being used instead of \o* and so I tried to fix this but then there are more errors with `unproj1` not being defined and so I was not sure how to continue

**Comment by effectfully** [comment]
Thank you, I did not realize everything needs to be buildable. That stuff was terribly outdated. Removed it and rereleased the library as v0.1.

**Comment by turion** [comment]
@effectfully Agda is a bit bare bones in that respect because it doesn't give you anything like a `*.cabal` file which lists all the modules that need to build. As far as I can tell, some (many?) other Agda libraries work around that by creating a file `Everything.agda` which simply import everything in the library. In fact, Alex is creating such a file in https://github.com/NixOS/nixpkgs/pull/95059 on the fly. So if you want to have more fine-grain control, you might want to create such a file yourself.
